CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(190) NOT NULL,
  name VARCHAR(120) NOT NULL,
  profile TEXT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(30) NOT NULL DEFAULT 'admin',
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  last_login_at DATETIME NULL,
  last_login DATETIME NULL,
  remember_token VARCHAR(255) NULL,
  remember_expires_at DATETIME NULL,
  force_password_change TINYINT(1) NOT NULL DEFAULT 0,
  failed_login_count INT UNSIGNED NOT NULL DEFAULT 0,
  locked_until DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY users_email_unique (email),
  KEY users_role_idx (role),
  KEY users_remember_idx (remember_token),
  KEY users_locked_idx (locked_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS members (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(190) NOT NULL,
  name VARCHAR(120) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  phone VARCHAR(40) NOT NULL DEFAULT '',
  organization VARCHAR(160) NOT NULL DEFAULT '',
  status ENUM('pending', 'approved', 'rejected', 'suspended') NOT NULL DEFAULT 'pending',
  memo TEXT NULL,
  approved_at DATETIME NULL,
  approved_by INT UNSIGNED NULL,
  last_login_at DATETIME NULL,
  failed_login_count INT UNSIGNED NOT NULL DEFAULT 0,
  locked_until DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY members_email_unique (email),
  KEY members_status_idx (status),
  KEY members_approved_by_idx (approved_by),
  KEY members_locked_idx (locked_until),
  CONSTRAINT members_approved_by_fk FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS settings (
  setting_key VARCHAR(80) NOT NULL,
  setting_value LONGTEXT NOT NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notices (
  id VARCHAR(120) NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT NULL,
  content MEDIUMTEXT NULL,
  body MEDIUMTEXT NULL,
  thumbnail VARCHAR(255) NOT NULL DEFAULT '',
  image VARCHAR(255) NOT NULL DEFAULT '',
  attachment_label VARCHAR(120) NOT NULL DEFAULT '첨부 자료 보기',
  attachment_url VARCHAR(255) NOT NULL DEFAULT '',
  attachment_file VARCHAR(255) NOT NULL DEFAULT '',
  icon VARCHAR(60) NOT NULL DEFAULT 'document',
  category VARCHAR(80) NOT NULL DEFAULT '공지',
  status ENUM('published', 'private', 'draft') NOT NULL DEFAULT 'published',
  author VARCHAR(120) NOT NULL DEFAULT '',
  views INT UNSIGNED NOT NULL DEFAULT 0,
  is_notice TINYINT(1) NOT NULL DEFAULT 0,
  is_pinned TINYINT(1) NOT NULL DEFAULT 0,
  pinned TINYINT(1) NOT NULL DEFAULT 0,
  important TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  post_date DATE NULL,
  published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY notices_status_date_idx (status, post_date),
  KEY notices_category_idx (category),
  FULLTEXT KEY notices_search_idx (title, summary, body)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS activities (
  id VARCHAR(120) NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT NULL,
  content MEDIUMTEXT NULL,
  body MEDIUMTEXT NULL,
  thumbnail VARCHAR(255) NOT NULL DEFAULT '',
  image VARCHAR(255) NOT NULL DEFAULT '',
  attachment_label VARCHAR(120) NOT NULL DEFAULT '첨부 자료 보기',
  attachment_url VARCHAR(255) NOT NULL DEFAULT '',
  attachment_file VARCHAR(255) NOT NULL DEFAULT '',
  icon VARCHAR(60) NOT NULL DEFAULT 'document',
  category VARCHAR(80) NOT NULL DEFAULT '활동',
  status ENUM('published', 'private', 'draft') NOT NULL DEFAULT 'published',
  author VARCHAR(120) NOT NULL DEFAULT '',
  views INT UNSIGNED NOT NULL DEFAULT 0,
  is_notice TINYINT(1) NOT NULL DEFAULT 0,
  is_pinned TINYINT(1) NOT NULL DEFAULT 0,
  pinned TINYINT(1) NOT NULL DEFAULT 0,
  important TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  post_date DATE NULL,
  published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY activities_status_date_idx (status, post_date),
  KEY activities_category_idx (category),
  FULLTEXT KEY activities_search_idx (title, summary, body)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS resources (
  id VARCHAR(120) NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT NULL,
  content MEDIUMTEXT NULL,
  body MEDIUMTEXT NULL,
  thumbnail VARCHAR(255) NOT NULL DEFAULT '',
  image VARCHAR(255) NOT NULL DEFAULT '',
  attachment_label VARCHAR(120) NOT NULL DEFAULT '자료 보기',
  attachment_url VARCHAR(255) NOT NULL DEFAULT '',
  attachment_file VARCHAR(255) NOT NULL DEFAULT '',
  icon VARCHAR(60) NOT NULL DEFAULT 'document',
  category VARCHAR(80) NOT NULL DEFAULT '자료',
  status ENUM('published', 'private', 'draft') NOT NULL DEFAULT 'published',
  author VARCHAR(120) NOT NULL DEFAULT '',
  views INT UNSIGNED NOT NULL DEFAULT 0,
  is_notice TINYINT(1) NOT NULL DEFAULT 0,
  is_pinned TINYINT(1) NOT NULL DEFAULT 0,
  pinned TINYINT(1) NOT NULL DEFAULT 0,
  important TINYINT(1) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  post_date DATE NULL,
  published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY resources_status_date_idx (status, post_date),
  KEY resources_category_idx (category),
  FULLTEXT KEY resources_search_idx (title, summary, body)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contacts (
  id VARCHAR(80) NOT NULL,
  title VARCHAR(120) NOT NULL,
  main_value VARCHAR(255) NOT NULL DEFAULT '',
  sub_value VARCHAR(255) NOT NULL DEFAULT '',
  icon VARCHAR(60) NOT NULL DEFAULT 'phone',
  map_provider VARCHAR(30) NOT NULL DEFAULT '',
  map_lat DECIMAL(10, 7) NULL,
  map_lng DECIMAL(10, 7) NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS admin_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT UNSIGNED NULL,
  action VARCHAR(80) NOT NULL,
  target_type VARCHAR(80) NOT NULL DEFAULT '',
  target_id VARCHAR(120) NULL,
  ip_address VARCHAR(45) NOT NULL DEFAULT '',
  user_agent VARCHAR(255) NOT NULL DEFAULT '',
  meta JSON NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY admin_logs_user_idx (user_id),
  KEY admin_logs_action_idx (action),
  KEY admin_logs_created_idx (created_at),
  CONSTRAINT admin_logs_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
